### ISSUE TITLE
RTGS form fields placement

### ISSUE THREAD

**Issue by abybaddi009** [ronbaddi004/Sequoia#1]
Consider the following:

1. The RTGS create form should have two columns.
2. The Customer fields should come before the RTGS model fields
3. The **amount in figures** field should span the entire width.

**Comment by ronbaddi004** [comment]
Issue [#1](https://github.com/ronbaddi004/Sequoia/commit/28c7201404e0ea44b0babd820282104874ea5a11) has been solved in this latest Commit @abybaddi009 .
